sudo: required

language: go

services:
  - docker

before_install:
- docker pull golang:1.10-alpine3.7
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
- make
- docker push blockchainworkers/conch