sudo: required

language: go

compiler:
  - clang
  - gcc

services:
  - docker

before_install:
- docker pull golang:1.10-alpine3.7
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
- docker build -t blockchainworkers/conch:latest ./docker/
- docker push blockchainworkers/conch